# Workflow 이름
name: CI/CD with Gradle

# Event 지정
on:
  push:
    branches: [ "main" ]

# Workflow 내 Job 을 정의
jobs:
  # Job 의 이름
  CI-CD-build:
    # Runner 환경 정의
    runs-on: ubuntu-latest

    # Step 정의
    steps:
    # 정의된 Actions 의 체크아웃 사용
    - uses: actions/checkout@v4

    # 1. jdk 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 2. Gradle Caching
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 3. craete firebase key
    - name: create firebase key
      run: |
        cd ./src/main/resources
        ls -a .
        touch ./firebase-service-key.json
        echo "${{ secrets.FIREBASE_KEY }}" > ./firebase-service-key.json
      shell: bash

    # 4. Gradle build
    - name: Build with Gradle Wrapper
      run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

    # 5. docker build & push
    - name: docker build and push
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/vitalroutes-spring ./
          docker push ${{ secrets.DOCKER_USERNAME }}/vitalroutes-spring

    # 6. Docker Compose Start
    - name: SSH into Ubuntu Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
           sudo docker rm -f $(docker ps -qa)
           sudo docker pull ${{ secrets.DOCKER_USERNAME }}/vitalroutes-spring
           sudo docker-compose up -d
